services:
    postgres:
                container_name: server-postgres
                image: postgres:latest
                restart: unless-stopped
                environment:
                    - POSTGRES_USER=server
                    - POSTGRES_PASSWORD=ed8ce181b15d873a3eb93f29
                    - POSTGRES_DB=server
                ports:
                    - 5432:5432
                volumes:
                    - postgres_data:/var/lib/postgresql/data
    redis:
                container_name: server-redis
                image: redis:latest
                command: [ "redis-server", "--maxmemory-policy", "noeviction" ]
                restart: unless-stopped
                ports:
                    - 6379:6379
                volumes:
                    - redis_data:/data
volumes:
    postgres_data:
    redis_data:
    
networks:
    default: {}