services:
    bot:
                container_name: server-bot
                restart: unless-stopped
                build:
                    context: .
                    dockerfile: Dockerfile
                environment:
                    - NODE_ENV=production
    postgres:
                container_name: server-postgres
                image: postgres:latest
                restart: unless-stopped
                environment:
                    - POSTGRES_USER=server
                    - POSTGRES_PASSWORD=ed8ce181b15d873a3eb93f29
                    - POSTGRES_DB=server
                volumes:
                    - postgres_data:/var/lib/postgresql/data
    redis:
                container_name: server-redis
                image: redis:latest
                command: [ "redis-server", "--maxmemory-policy", "noeviction" ]
                restart: unless-stopped
                volumes:
                    - redis_data:/data
volumes:
    postgres_data:
    redis_data:
    
networks:
    default: {}